language: java
jdk:
  - openjdk11

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - TEST_SUITE=api

before_install:
  - sudo service mysql stop
  - wget https://services.gradle.org/distributions/gradle-5.6-bin.zip
  - unzip -qq gradle-5.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

install:
  - |
    if [ "${TEST_SUITE}" == "api" ]; then
      gradle assemble
    fi
script:
  - |
    if [ "${TEST_SUITE}" == "api" ]; then
      SPRING_PROFILES_ACTIVE=docker gradle check dockerApiTest
    fi
